packages:
  - "examples/*"
  - "packages/*"
  - "test/*"

onlyBuiltDependencies:
  - "better-sqlite3"
  - "esbuild"

overrides:
  "better-sqlite3": "12.10.0"

catalog:
  effect: 4.0.0-rc.112
  "@effect/platform-node": 4.0.0-rc.112
  "@effect/sql-pg": 4.0.0-rc.112
  "@effect/sql-sqlite-node": 4.0.0-rc.112
  "@effect/vitest": 4.0.0-rc.112
  tsdown: 0.21.7
  tsx: 4.19.0
  typescript: 6.0.2
  vitest: 4.1.11
  "@types/node": 25.9.1
  ulidx: 2.4.1
