/**
 * SPARQL Schema - Re-export from domain package
 */

// Effect Schema objects
export {
  Variable,
  IRI,
  Constant,
  Term,
  TriplePattern,
  ComparisonOp,
  LogicalOp,
  BuiltInFunction,
  ComparisonExpr,
  BuiltInCall,
  FilterExpression,
  MathOp,
  BindExpression,
  PropertyPath,
  OptionalPattern,
  UnionPattern,
  FilterPattern,
  BindPattern,
  ValuesPattern,
  MinusPattern,
  PropertyPathPattern,
  SubSelectPattern,
  GraphPatternElement,
  GraphPattern,
  AggregateOp,
  AggregateSpec,
  OrderDirection,
  OrderBySpec,
  HavingClause,
  QueryForm,
  SelectClause,
  SparqlQuery,
  // Helper functions
  isVariable,
  isIRI,
  isTriplePattern,
  isOptionalPattern,
  isUnionPattern,
  isFilterPattern,
  isBindPattern,
  isValuesPattern,
  isMinusPattern,
  isPropertyPathPattern,
  isSubSelectPattern,
  isComparisonExpr,
  isBuiltInCall,
  isLogicalExpr,
  isExistsExpr,
  isSimplePath,
  isSeqPath,
  isAltPath,
  isInversePath,
  isZeroOrMorePath,
  isOneOrMorePath,
  isZeroOrOnePath,
} from "../Sparql.js";

// Re-export types explicitly
export type { LogicalExpr, ExistsExpr } from "../Sparql.js";
